### ISSUE TITLE
Linux/OSX compatibility

### ISSUE THREAD

**Issue by tcastelly** [sekigon-gonnoc/keyboard-quantizer-doc#5]
Hello,

I'm sorry if it's not the good place to ask. 
I'm wondering if the "Keyboard Quantizer Mini" works with Linux and OSX. I'm asking because in the documentation it said:

```The companion app is implemented with PowerShell scripts that can be sent to your PC from your keyboard and run, so you don't need to install any additional software on your PC.```
https://booth.pm/ja/items/4823647

Thank you very much.

**Comment by sekigon-gonnoc** [comment]
Yes, it works with Linux and OSX. 
The companion app allows key remapping for each active application on your PC. This app is available for Windows only

**Comment by tcastelly** [comment]
Perfect, thank you very much!
