### ISSUE TITLE
Remapでの Flash と マクロ設定

### ISSUE THREAD

**Issue by SJ1700** [sekigon-gonnoc/keyboard-quantizer-doc#8]
Keyboard Quantizer Miniを使用しています。ファームウェアは最新([keyboard_quantizer_mini_via_default.uf2)を入れています。

Remapで設定後、「Flash」をクリックする度に Remapから切断されます。また、複数のキー変更をした場合、全ての変更が反映されません(最初に変更した設定だけが反映される)。これは正しい挙動でしょうか。

また、マクロ設定後に、再度設定したマクロをクリックすると「Not end with a null character.」とエラーが表示されます。

上記の回答・回避策を教えて頂けると助かります。

**Comment by sekigon-gonnoc** [comment]
Full版のファームウェアを試していただけますか？
https://github.com/sekigon-gonnoc/keyboard-quantizer-doc/tree/master/mini#%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%82%A6%E3%82%A7%E3%82%A2%E3%81%AE%E6%9B%B8%E3%81%8D%E6%8F%9B%E3%81%88%E6%96%B9%E6%B3%95

**Comment by SJ1700** [comment]
早急に回答ありがとうございます。
Full版だと、Remapは使えず、Keyboard Quantizer Config Generatorで設定するという認識でしょうか。
https://sekigon-gonnoc.github.io/keyboard-quantizer-config-generator/

尚、マクロなどの詳細な設定をしなければ、以下の QMK Configuratorで設定は可能でしょうか。
https://sekigon-gonnoc.github.io/qmk_configurator/#/0_sixty/base/LAYOUT_1x2uC

初歩的な質問で申し訳ございませんが、よろしくお願いいたします。

**Comment by sekigon-gonnoc** [comment]
Keyboard Quantizer Config Generatorで設定することになります。QMK Configuratorは使用できません

**Comment by SJ1700** [comment]
ありがとうございます！承知しました。
